# Generated by Django 5.2.8 on 2025-11-17 17:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
                'db_table': 'customer_segment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_type', models.CharField(choices=[('new_menu', 'new_menu'), ('seasonal', 'seasonal'), ('event', 'event'), ('flash_sale', 'flash_sale'), ('other', 'other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('active', 'active'), ('paused', 'paused'), ('completed', 'completed')], default='draft', max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_audience_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaign.customersegment')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_sent', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_delivered', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_opened', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_clicked', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_conversions', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('roi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Analytics',
                'verbose_name_plural': 'Campaign Analytics',
                'db_table': 'campaign_analytics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at'], name='campaign_an_recorde_a68601_idx'), models.Index(fields=['campaign', 'recorded_at'], name='campaign_an_campaig_bd8f0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('whatsapp', 'whatsapp'), ('social', 'social'), ('push', 'push'), ('other', 'other')], max_length=30)),
                ('message_template', models.TextField(blank=True, null=True)),
                ('subject_line', models.CharField(blank=True, max_length=255, null=True)),
                ('content_body', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('sent', 'sent'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='draft', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Message',
                'verbose_name_plural': 'Campaign Messages',
                'db_table': 'campaign_message',
                'ordering': ['-scheduled_time', '-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaign_me_campaig_8af918_idx')],
            },
        ),
    ]
