# Generated by Django 5.2.8 on 2025-11-19 10:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(help_text='Unique QR code identifier', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('qr_type', models.CharField(choices=[('table', 'table'), ('campaign', 'campaign'), ('location', 'location'), ('event', 'event')], max_length=20)),
                ('redirect_action', models.CharField(blank=True, choices=[('app_download', 'app_download'), ('signup', 'signup'), ('ordering', 'ordering'), ('contact', 'contact')], max_length=30, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('landing_page_config', models.JSONField(blank=True, default=dict)),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_text', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('max_scans', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_scans', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'qr_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='qr_code_tenant__7842c9_idx'), models.Index(fields=['is_active'], name='qr_code_is_acti_1f776c_idx')],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('desktop', 'Desktop')], max_length=20, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('action_taken', models.CharField(choices=[('signed_up', 'signed_up'), ('downloaded', 'downloaded'), ('ordered', 'ordered'), ('none', 'none')], default='none', max_length=30)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qrCodeMarketing.qrcode')),
            ],
            options={
                'verbose_name': 'QR Code Scan',
                'verbose_name_plural': 'QR Code Scans',
                'db_table': 'qr_code_scan',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['qr_code', 'scanned_at'], name='qr_code_sca_qr_code_31e6e7_idx'), models.Index(fields=['customer_id'], name='qr_code_sca_custome_ae2a6c_idx')],
            },
        ),
    ]
