# Generated by Django 5.2.8 on 2025-11-19 09:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('published', 'published'), ('failed', 'failed')], default='draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('post', 'post'), ('story', 'story'), ('reel', 'reel'), ('video', 'video')], default='post', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='campaign.campaign')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'db_table': 'social_media_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPostMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('x', 'x'), ('tiktok', 'tiktok')], max_length=30)),
                ('platform_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('likes_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shares_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reach', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('impressions', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clicks', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='socialMedia.socialmediapost')),
            ],
            options={
                'verbose_name': 'Social Media Post Metrics',
                'verbose_name_plural': 'Social Media Post Metrics',
                'db_table': 'social_media_post_metrics',
                'ordering': ['-last_synced_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['campaign', 'status'], name='social_medi_campaig_9852f3_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapost',
            index=models.Index(fields=['tenant_id'], name='social_medi_tenant__ccbbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediapostmetrics',
            index=models.Index(fields=['social_media_post', 'platform'], name='social_medi_social__0f0a1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediapostmetrics',
            unique_together={('social_media_post', 'platform')},
        ),
    ]
