# Generated by Django 5.2.8 on 2025-11-19 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('template_id', models.CharField(help_text='WhatsApp approved template ID', max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('header_type', models.CharField(blank=True, choices=[('text', 'text'), ('image', 'image'), ('video', 'video'), ('document', 'document')], max_length=20, null=True)),
                ('header_content', models.TextField(blank=True, null=True)),
                ('body_content', models.TextField()),
                ('footer_content', models.TextField(blank=True, null=True)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('approval_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'db_table': 'whatsapp_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='whatsapp_te_tenant__3e6a3c_idx'), models.Index(fields=['template_id'], name='whatsapp_te_templat_13bdcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('promotional', 'promotional'), ('transactional', 'transactional'), ('utility', 'utility')], default='promotional', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed')], default='draft', max_length=20)),
                ('sent_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivered_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('read_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('replied_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to='campaign.campaign')),
                ('customer_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_campaigns', to='campaign.customersegment')),
                ('whatsapp_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='whatsappMarketing.whatsapptemplate')),
            ],
            options={
                'verbose_name': 'WhatsApp Campaign',
                'verbose_name_plural': 'WhatsApp Campaigns',
                'db_table': 'whatsapp_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('message_id', models.CharField(blank=True, help_text='WhatsApp message ID', max_length=255, null=True)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read'), ('failed', 'failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsappMarketing.whatsappcampaign')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'db_table': 'whatsapp_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['whatsapp_campaign', 'status'], name='whatsapp_me_whatsap_db9a4b_idx'), models.Index(fields=['message_id'], name='whatsapp_me_message_dc4b4e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcampaign',
            index=models.Index(fields=['campaign', 'status'], name='whatsapp_ca_campaig_d788dc_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaign',
            index=models.Index(fields=['tenant_id'], name='whatsapp_ca_tenant__393017_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaign',
            index=models.Index(fields=['scheduled_time'], name='whatsapp_ca_schedul_03379f_idx'),
        ),
    ]
