# Generated by Django 5.2.8 on 2025-11-19 09:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('welcome', 'welcome'), ('birthday', 'birthday'), ('promo', 'promo'), ('newsletter', 'newsletter'), ('other', 'other')], default='other', max_length=50)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_platform_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='email_templ_tenant__9de6ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subject_line', models.CharField(max_length=255)),
                ('preview_text', models.CharField(blank=True, max_length=255, null=True)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personalization_fields', models.JSONField(blank=True, default=dict)),
                ('ab_test_enabled', models.BooleanField(default=False)),
                ('ab_test_variant', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('winner', 'winner')], max_length=10, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed')], default='draft', max_length=20)),
                ('sent_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivered_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('opened_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clicked_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bounced_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unsubscribed_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='campaign.campaign')),
                ('customer_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to='campaign.customersegment')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to='emailMarketing.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'db_table': 'email_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('opened', 'opened'), ('clicked', 'clicked'), ('bounced', 'bounced'), ('unsubscribed', 'unsubscribed')], max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('link_clicked', models.URLField(blank=True, null=True)),
                ('bounce_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='emailMarketing.emailcampaign')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'db_table': 'email_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email_campaign', 'event_type', 'timestamp'], name='email_event_email_c_23ba18_idx'), models.Index(fields=['customer_id'], name='email_event_custome_1904ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['campaign', 'status'], name='email_campa_campaig_f483f2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['tenant_id'], name='email_campa_tenant__d65cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['scheduled_time'], name='email_campa_schedul_9683f3_idx'),
        ),
    ]
